404.htmlを記述
Treasure-Hunting/Backend pull request #61
Opened 2019-09-22 11:11 UTC by Snowman-s

2019-09-22 11:38 UTC, siketyan requested changes

2019-09-22 11:38 UTC, Siketyan commented on oursite/treasure/templates/404.html
> +    404エラーです。係員にお伝えください。
> 404エラー

 という表現は HTTP ステータスコードを知らない人には伝わらない表現なので，

> 存在しないページに遷移しようとしました．

などとするべきかと思います．

2019-09-22 11:38 UTC, Siketyan commented on oursite/treasure/templates/404.html
> +</p>
```suggestion
</p>

```

2019-09-22 13:14 UTC, Snowman-s commented on oursite/treasure/templates/404.html
> +    404エラーです。係員にお伝えください。
こちら側のバグや仕様で404に飛ぶならまだしも、
URL直打ちやページバックした(かつ出てくるページバックはダメというメッセージを拒否した)ときにこうなるのを想定しているので、そのレベルの人は404エラーを理解していると思いこのメッセージを作成しました。詳しい文言はフロントエンドに任して、ただ単にこれは仮のメッセージであるため、これは解決済みにしていただけないですか。

2019-09-24 07:58 UTC, Snowman-s commented
レビューお願いします

2019-10-03 09:49 UTC, unitl-kr approved these changes

2019-10-10 00:00 UTC, m-star18 approved these changes

2019-10-20 09:13 UTC, Snowman-s commented
なんでこれChengeRequestsがついたままになってますかねぇ...

2019-10-23 01:26 UTC, Snowman-s commented
よく考えたらフロントエンドに委託すればいいだけでしたね

2019-10-23 01:26 UTC, closed without merging